name: ðŸŸ¨ Basic Example

on:
  push:
    branches:
      - main
    
  workflow_dispatch:

permissions:
  contents: read
  issues: write
jobs:
  plan-apply:
    runs-on: ubuntu-latest
    name: Plan -> Apply
    steps:
      - uses: actions/checkout@v5
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Plan and Apply
        uses: jlroskens/tofu-plan-approve-apply@v1
        with:
          working-directory: examples/basic
      - name: Outputs
        shell: bash
        run: |
          echo "Random Number: $(tofu output -raw random_value)"
         