name: ðŸŸ¨ Variables Example

on:
  push:
    branches:
      - main
      - feature/init-var-args
    
  workflow_dispatch:

permissions:
  contents: read
  issues: write
jobs:
  plan-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
      
      - name: Create .terraform Directory
        shell: bash
        run: mkdir -p .terraform

      - name: Plan and Apply
        uses: jlroskens/tofu-plan-approve-apply@feature/init-var-args
        with:
          working-directory: examples/variables
          var-files: |-
            example.tfvars
          vars: |-
             state_file_path=.terraform/variables_example.tfstate
          init-vars-enabled: true
      
      - name: Outputs
        shell: bash
        run: |
          echo "Random Number: $(tofu output -raw random_value)"
          echo "State File:" 
          ls -l .terraform/variables_example.tfstate